[package]
name = "scrape"
version = "0.1.0"
edition = "2021"

[dependencies]
encoding_rs = "0.8.35"
encoding_rs_io = "0.1.7"
regex = "1.11.1"
reqwest = "0.12.8"
scraper = "0.20.0"
serde = "1.0.214"
serde_json = "1.0.132"
tokio = { version = "1.41.0", features = ["full"] }
